### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by alansemenov**

### CODE REVIEW

**Comment by sigdestad** [comment]
Awesome stuff Alan, but afaik the implementation here does not solve unique urls across apps? I.e. same problem as posten has? Why not mount serving of static assets as a service?

**Comment by sigdestad** [comment]
Also, would love to rename getAssetUrl, staticAssetUrl, or something like that instead?

**Comment by alansemenov** [comment]
> Awesome stuff Alan, but afaik the implementation here does not solve unique urls across apps? I.e. same problem as posten has? Why not mount serving of static assets as a service?

Because this is not a starter? I don't see a reason to solve this issue for the tutorial, it's not meant to be used for building multiple apps. Should be solved in the tsup starter.

**Comment by alansemenov** [comment]
> Also, would love to rename getAssetUrl, staticAssetUrl, or something like that instead?

Done

**Pull request merged**
